import logging
import re
from datetime import datetime

from agents.state import InboundState
from lib.routing import front_matter
from lib.security import redact_pii
from tools.file_tools import write_report

logger = logging.getLogger(__name__)


class HandoffWriterError(Exception):
    pass


class HandoffWriter:
    """Writes an inbound triage note: either a reply draft or a human handoff."""

    def write(self, state: InboundState) -> str:
        """Build and write the inbound note.

        Args:
            state (InboundState): fully populated inbound pipeline state

        Returns:
            str: absolute path of the written file
        """
        message = state.get("message", {})
        triage = state.get("triage", {})
        routing = state.get("routing", {})
        reply = state.get("reply", {})
        handoff = state.get("handoff", {})

        sender = message.get("sender", "unknown")
        slug = re.sub(r"[^a-z0-9]+", "_", sender.lower()).strip("_") or "inbound"
        run_suffix = state.get("run_id", "")[:8]
        filename = f"inbound_{slug}_{run_suffix}.md"
        date = datetime.now().strftime("%Y-%m-%d %H:%M")

        escalated = bool(routing.get("escalate"))
        heading = "Escalation" if escalated else "Reply Draft"

        md = f"""{front_matter(state.get("run_id", ""), "inbound", routing)}

# Inbound {heading}: {sender}

**Received:** {date}
**Channel:** {message.get('channel', 'email')}
**Subject:** {message.get('subject', '')}

---

## 1. Triage

| Signal | Value |
| --- | --- |
| Sentiment | {triage.get('sentiment', 'unknown')} |
| Intent | {triage.get('intent', 'unknown')} |
| Urgency | {triage.get('urgency', 'unknown')} |

**Summary:** {triage.get('summary', '_Not available._')}

### Key Points

{_bullet_list(triage.get('key_points', []))}

---

## 2. Routing

| Field | Value |
| --- | --- |
| Queue | {routing.get('queue', 'unassigned')} |
| Priority | {routing.get('priority', 'normal')} |
| Owner | {routing.get('owner', 'unassigned')} |
| Escalated | {'yes' if escalated else 'no'} |

**Reason:** {routing.get('reason', '_Not recorded._')}

---

{_body_section(escalated, reply, handoff)}

---

## 4. Original Message

{message.get('body', '')}

---

*Generated by Customer Outreach Automation Agent — inbound pipeline.*
*{'This message was escalated; no reply was drafted.' if escalated else 'This is a DRAFT. A human must review and send it.'}*
"""

        md = redact_pii(md)

        result = write_report(filename=filename, content=md)
        if result.get("status") != "written":
            raise HandoffWriterError(f"Failed to write note: {result.get('status')}")

        return result["path"]


def _body_section(escalated: bool, reply: dict, handoff: dict) -> str:
    if escalated:
        return f"""## 3. Handoff Brief

**Assigned to:** {handoff.get('owner', 'unassigned')}
**Priority:** {handoff.get('priority', 'normal')}

{handoff.get('summary', '_No summary available._')}

### Context for the responder

{_bullet_list(handoff.get('key_points', []))}

### Identifiers

{_entity_list(handoff.get('entities', {}))}"""

    open_questions = reply.get("open_questions", [])
    return f"""## 3. Reply Draft

**Subject:** {reply.get('subject', '')}

{reply.get('body', '_No draft generated._')}

**Tone:** {reply.get('tone', 'N/A')}
**Confidence:** {reply.get('confidence', 'N/A')}/10

### Open Questions

{_bullet_list(open_questions) if open_questions else '_None — the draft answers the message in full._'}"""


def _bullet_list(items) -> str:
    if not items:
        return "_None recorded._"
    if isinstance(items, str):
        return f"- {items}"
    return "\n".join(f"- {item}" for item in items)


def _entity_list(entities) -> str:
    if not entities:
        return "_None identified._"
    return "\n".join(f"- **{key}:** {value}" for key, value in entities.items())
