import logging
import re
from datetime import datetime

from agents.state import OutreachState
from lib.security import redact_pii
from tools.file_tools import write_report

logger = logging.getLogger(__name__)


class ReportWriterError(Exception):
    pass


class ReportWriter:
    """Assembles specialist outputs into a Markdown lead report and writes it to disk."""

    def write(self, state: OutreachState) -> str:
        """Build and write the lead report.

        Args:
            state (OutreachState): fully populated pipeline state

        Returns:
            str: absolute path of the written file
        """
        lead = state.get("lead", {})
        research = state.get("research_data", {})
        mkt = state.get("marketing_data", {})
        sales = state.get("sales_data", {})
        evaluation = state.get("evaluation", {})
        routing = state.get("routing", {})

        company = lead.get("company", "Unknown")
        slug = re.sub(r"[^a-z0-9]+", "_", company.lower()).strip("_")
        filename = f"{slug}_lead_report.md"
        date = datetime.now().strftime("%Y-%m-%d")

        email = sales.get("email", {})
        subject = email.get("subject", "")
        body = email.get("body", "")

        md = f"""# Lead Report: {company}

{_status_banner(routing, evaluation)}

**Generated:** {date}
**Website:** {lead.get('url', '')}

---

## 1. Company Profile

{research.get('profile', '_No profile available._')}

### Recent News

{_bullet_list(research.get('news', []))}

### Key People

{_bullet_list(research.get('people', []))}

### Technology Stack

{_bullet_list(research.get('tech_stack', []))}

### Pain Points

{_bullet_list(research.get('pain_points', []))}

---

## 2. Marketing Strategy

**ICP Fit:** {mkt.get('icp_fit', 'N/A')}

**Recommended Tone:** {mkt.get('tone', 'N/A')}

**Opening Hook:** {mkt.get('hook', '')}

### Value Propositions

{_numbered_list(mkt.get('value_props', []))}

### Competitor Positioning

{mkt.get('positioning', '_Not available._')}

**Key Competitors:** {', '.join(mkt.get('competitors', []))}

---

## 3. Sales Outreach

### Cold Email

**Subject:** {subject}

{body}

---

### LinkedIn Connection Note

{sales.get('linkedin', '_Not generated._')}

---

### Follow-Up Sequence

{_followup_block(sales.get('followups', []))}

---

## 4. Objection Handling

{_objection_block(sales.get('objections', []))}

---

## 5. Recommended Next Action

{sales.get('next_action', '_Not specified._')}

---

## 6. Quality Review

{_evaluation_block(evaluation)}

---

## 7. Routing

{_routing_block(routing)}

---

*Report generated by Customer Outreach Automation Agent*
"""

        md = redact_pii(md)

        result = write_report(filename=filename, content=md)
        if result.get("status") != "written":
            raise ReportWriterError(f"Failed to write report: {result.get('status')}")

        return result["path"]



# Markdown helpers
def _status_banner(routing: dict, evaluation: dict) -> str:
    """Lead with the verdict.

    An escalated report that looks identical to an approved one makes the review
    gate decorative — whoever opens this has to see the status before the draft.
    """
    if not routing and not evaluation:
        return "> **Status:** not reviewed."

    overall = evaluation.get("overall", "N/A")
    if routing.get("escalate"):
        return (
            f"> ## \u26a0 NEEDS HUMAN REVIEW — DO NOT SEND AS-IS\n"
            f"> \n"
            f"> Quality score **{overall}/10**. "
            f"Routed to **{routing.get('owner', 'unassigned')}** "
            f"({routing.get('queue', 'unassigned')}).\n"
            f"> \n"
            f"> {routing.get('reason', '')}"
        )
    return (
        f"> **Approved for outreach** — quality score **{overall}/10**, "
        f"routed to **{routing.get('owner', 'unassigned')}** "
        f"({routing.get('queue', 'standard')} queue)."
    )


def _evaluation_block(evaluation: dict) -> str:
    if not evaluation:
        return "_This draft was not reviewed._"

    scores = evaluation.get("scores") or {}
    score_rows = "\n".join(
        f"| {key.replace('_', ' ').title()} | {value}/10 |" for key, value in scores.items()
    ) or "| _No component scores recorded._ | |"

    issues = evaluation.get("issues") or []
    critique = str(evaluation.get("critique", "")).strip()

    return f"""**Verdict:** {evaluation.get('verdict', 'unknown')}
**Overall:** {evaluation.get('overall', 'N/A')}/10
**Reads as:** {evaluation.get('sentiment', 'unknown')}

| Dimension | Score |
| --- | --- |
{score_rows}

### Issues Raised

{_bullet_list(issues) if issues else '_None._'}

### Reviewer Notes

{critique if critique else '_None._'}"""


def _routing_block(routing: dict) -> str:
    if not routing:
        return "_Not routed._"
    return f"""| Field | Value |
| --- | --- |
| Queue | {routing.get('queue', 'unassigned')} |
| Priority | {routing.get('priority', 'normal')} |
| Owner | {routing.get('owner', 'unassigned')} |
| Escalated | {'yes' if routing.get('escalate') else 'no'} |

**Reason:** {routing.get('reason', '_Not recorded._')}"""


def _bullet_list(items) -> str:
    if not items:
        return "_None found._"
    if isinstance(items, str):
        return f"- {items}"
    return "\n".join(f"- {item}" for item in items)


def _numbered_list(items) -> str:
    if not items:
        return "_None found._"
    return "\n".join(f"{i}. {item}" for i, item in enumerate(items, 1))


def _followup_block(followups) -> str:
    if not followups:
        return "_Not generated._"
    blocks = []
    for i, msg in enumerate(followups, 1):
        blocks.append(f"**Follow-up {i} (Day {i * 7}):**\n\n{msg}")
    return "\n\n".join(blocks)


def _objection_block(objections) -> str:
    if not objections:
        return "_Not generated._"
    blocks = []
    for obj in objections:
        o = obj.get("objection", "")
        r = obj.get("response", "")
        blocks.append(f"**Objection:** {o}\n\n**Response:** {r}")
    return "\n\n---\n\n".join(blocks)
